### ISSUE TITLE
Get single Haiku doesn't work - only returns an empty array

### ISSUE THREAD

**Issue by Dpalazzari** [daltonwais/basho-haiku#1]
Shit dont work @daltonwais 

<img width="412" alt="screen shot 2018-04-04 at 9 41 24 pm" src="https://user-images.githubusercontent.com/19585280/38346244-0350b6d2-3851-11e8-89a3-5ff00106c998.png">

**Comment by Dpalazzari** [comment]
Same with the random endpoint

**Comment by Dpalazzari** [comment]
Before you ask, yes I created some Haikus:

<img width="521" alt="screen shot 2018-04-04 at 10 19 05 pm" src="https://user-images.githubusercontent.com/19585280/38347071-3ae0c9ac-3856-11e8-98ff-478091b77ebb.png">

**Comment by daltonwais** [comment]
your haikus don't have Titles.  That's how the single endpoint searches.  Not sure what the issue with the random endpoint is.  

Is mongo running?  Are the records making it into mongo?  Does the "/api/haikus" endpoint return anything?  It should return ALL.

**Comment by Dpalazzari** [comment]
I had 'title' instead of 'Title' in my request body. lol

**Comment by daltonwais** [comment]
@Dpalazzari what was the behavior?  Was it rejecting the save or just omitting that field?

**Comment by Dpalazzari** [comment]
It saved the json into mongo, just without a title
